# install some common packages which shouldn't be missing
# this includes a text editor, git, wget, curl, etc.
# The list can be extended as needed
# pay attention that the packages in this list should be available for linuxmint and debian
- name: Install basic foundation
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - vim  # never install emacs!
      - git
      - htop
      - curl
      - wget
      - tmux
  notify: Reboot if packages were installed

# afterwards install aditional packages only for the mgmt group
- name: Install additional packages for mgmt group
  ansible.builtin.apt:
    state: present
    name:
      - nmap
  when: "'mgmt' in group_names"

- name: Add a list of aliases into the .bashrc file of the mgmt machine
  ansible.builtin.blockinfile:
    path: /root/.bashrc
    append_newline: true
    prepend_newline: true
    block: |
      # Aliases
      alias ls="ls -F --color=auto"
      alias la="ls -a"
      alias ll="ls -laFh"
      alias grep="grep --color=auto"
  when: "'mgmt' in group_names"
